### ISSUE TITLE
Analyse syntaxique des documents HTML

### ISSUE THREAD

**Issue by PhiSyX** [PhiSyX/resworb#1]
Pour pouvoir parser correctement l'HTML, on a besoin d'implémenter les choses suivantes: (liste non exhaustive)

- [ ] Erreurs d'analyse syntaxique.#10
  - [x] abrupt-closing-of-empty-comment #13
  - [x] abrupt-doctype-public-identifier #5
  - [x] abrupt-doctype-system-identifier #5
  - [x] absence-of-digits-in-numeric-character-reference #15
  - [x] cdata-in-html-content #25
  - [x] character-reference-outside-unicode-range #15
  - [ ] control-character-in-input-stream
  - [x] control-character-reference #15
  - [ ] end-tag-with-attributes
  - [ ] duplicate-attribute
  - [ ] end-tag-with-trailing-solidus
  - [x] eof-before-tag-name
  - [x] eof-in-cdata #25
  - [x] eof-in-comment #13
  - [x] eof-in-doctype #5
  - [x] eof-in-script-html-comment-like-text #23
  - [x] eof-in-tag
  - [x] incorrectly-closed-comment #13
  - [x] incorrectly-opened-comment #13
  - [x] invalid-character-sequence-after-doctype-name #5
  - [x] invalid-first-character-of-tag-name
  - [x] missing-attribute-value
  - [x] missing-doctype-name #5
  - [x] missing-doctype-public-identifier #5
  - [x] missing-doctype-system-identifier #5
  - [x] missing-end-tag-name
  - [x] missing-quote-before-doctype-public-identifier #5
  - [x] missing-quote-before-doctype-system-identifier #5
  - [x] missing-semicolon-after-character-reference #15
  - [x] missing-whitespace-after-doctype-public-keyword #5
  - [x] missing-whitespace-after-doctype-system-keyword #5
  - [x] missing-whitespace-before-doctype-name #5
  - [x] missing-whitespace-between-attributes #5
  - [x] missing-whitespace-between-doctype-public-and-system-identifiers #5
  - [x] nested-comment #13
  - [x] noncharacter-character-reference #15
  - [ ] noncharacter-in-input-stream
  - [ ] non-void-html-element-start-tag-with-trailing-solidus
  - [x] null-character-reference #15
  - [x] surrogate-character-reference #15
  - [ ] surrogate-in-input-stream
  - [x] unexpected-character-after-doctype-system-identifier #5
  - [x] unexpected-character-in-attribute-name
  - [x] unexpected-character-in-unquoted-attribute-value
  - [x] unexpected-equals-sign-before-attribute-name
  - [x] unexpected-null-character
  - [x] unexpected-question-mark-instead-of-tag-name
  - [x] unexpected-solidus-in-tag
  - [x] unknown-named-character-reference #15
- [ ] État de l'analyse syntaxique.
  - [ ] Mode insertion
  - [ ] Pile d'éléments ouverts
  - [ ] Liste des éléments de mise en forme actifs
  - [ ] Les pointeurs d'éléments
  - [ ] drapeaux 
- [x] Tokenisation
  - [x] Data state
  - [x] RCDATA state #17
  - [x] RAWTEXT state #20
  - [x] Script data state #23
  - [x] #24
  - [x] Tag open state
  - [x] End tag open state
  - [x] Tag name state
  - [x] RCDATA less-than sign state #17
  - [x] RCDATA end tag open state #17
  - [x] RCDATA end tag name state #17
  - [x] RAWTEXT less-than sign state #20
  - [x] RAWTEXT end tag open state #20
  - [x] RAWTEXT end tag name state #20
  - [x] Script data less-than sign state #23
  - [x] Script data end tag open state #23
  - [x] Script data end tag name state #23
  - [x] Script data escape start state #23
  - [x] Script data escape start dash state #23 
  - [x] Script data escaped state #23
  - [x] Script data escaped dash state #23
  - [x] Script data escaped dash dash state #23
  - [x] Script data escaped less-than sign state #23
  - [x] Script data escaped end tag open state #23
  - [x] Script data escaped end tag name state #23
  - [x] Script data double escape start state #23
  - [x] Script data double escaped state #23
  - [x] Script data double escaped dash state #23
  - [x] Script data double escaped dash dash state #23
  - [x] Script data double escaped less-than sign state #23
  - [x] Script data double escape end state #23
  - [x] Before attribute name state #3
  - [x] Attribute name state #3
  - [x] After attribute name state #3
  - [x] Before attribute value state #3
  - [x] Attribute value (double-quoted) state #3
  - [x] Attribute value (single-quoted) state #3
  - [x] Attribute value (unquoted) state #3
  - [x] After attribute value (quoted) state #3
  - [x] Self-closing start tag state #12
  - [x] Bogus comment state #13
  - [x] Markup declaration open state
  - [x] Comment start state  #13
  - [x] Comment start dash state  #13
  - [x] Comment state  #13
  - [x] Comment less-than sign state  #13
  - [x] Comment less-than sign bang state  #13
  - [x] Comment less-than sign bang dash state  #13
  - [x] Comment less-than sign bang dash dash state  #13
  - [x] Comment end dash state  #13
  - [x] Comment end state  #13
  - [x] Comment end bang state  #13
  - [x] DOCTYPE state #5
  - [x] Before DOCTYPE name state #5
  - [x] DOCTYPE name state #5
  - [x] After DOCTYPE name state #5
  - [x] After DOCTYPE public keyword state #5
  - [x] Before DOCTYPE public identifier state #5
  - [x] DOCTYPE public identifier (double-quoted) state #5
  - [x] DOCTYPE public identifier (single-quoted) state #5
  - [x] After DOCTYPE public identifier state #5
  - [x] Between DOCTYPE public and system identifiers state #5
  - [x] After DOCTYPE system keyword state #5
  - [x] Before DOCTYPE system identifier state #5
  - [x] DOCTYPE system identifier (double-quoted) state #5
  - [x] DOCTYPE system identifier (single-quoted) state #5
  - [x] After DOCTYPE system identifier state #5
  - [x] Bogus DOCTYPE state #5
  - [x] CDATA section state #25
  - [x] CDATA section bracket state #25
  - [x] CDATA section end state #25
  - [x] Character reference state #15
  - [x] Named character reference state #15
  - [x] Ambiguous ampersand state #15
  - [x] Numeric character reference state #15
  - [x] Hexadecimal character reference start state #15
  - [x] Decimal character reference start state #15
  - [x] Hexadecimal character reference state #15
  - [x] Decimal character reference state #15
  - [x] Numeric character reference end state #15
- [ ] #28
