### ISSUE TITLE
CSS: syntaxe du CSS

### ISSUE THREAD

**Issue by PhiSyX** [PhiSyX/resworb#2]
Pour pouvoir parser correctement le CSS, on a besoin d'implémenter les choses suivantes: (liste non exhaustive)

- [x] #76
  - [x] Consommer les commentaires (résolu dans #76)
  - [x] Consommer un jeton numérique (résolu dans #76)
  - [x] Consommer un jeton ident-like (résolu dans #76)
  - [x] Consommer un jeton de chaine de caractère (résolu dans #76)
  - [x] Consommer un jeton URL (résolu dans #76)
  - [x] Consommer un point de code échappé (résolu dans #76)
  - [x] Vérifier si deux points de code constituent un échappement valide (résolu dans #76)
  - [x] Vérifier si trois points de code permettent de lancer une séquence d'identification (résolu dans #76)
  - [x] Vérifier si trois points de code permettent de commencer un nombre (résolu dans #76)
  - [x] Consommer une séquence d'identification (résolu dans #76)
  - [x] Consommer un nombre (résolu dans #76)
  - [x] Convertir une chaîne de caractères vers un nombre (résolu dans #76)
  - [x] Consommer les restes d'une mauvaise url (résolu dans #76)
- [x] #79
