### ISSUE TITLE
HTML Tokenization: CDATA

### ISSUE THREAD

**Issue by PhiSyX** [PhiSyX/resworb#25]
Concerne les états suivants : 

- [x] CDATA section state #25
- [x] CDATA section bracket state #25
- [x] CDATA section end state #25

**Comment by PhiSyX** [comment]
#1
